name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate: true
          activate-environment: languagetool-wrapper
          environment-file: environment.yml

      - name: Analysing the code with pylint
        run: |
          # This command now works because the environment is activated
          # and has pylint installed.
          pylint $(git ls-files '*.py')
